name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Landing Page
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/orakysec/france-at-home-landing:latest

      - name: Build and push Tracker
        uses: docker/build-push-action@v4
        with:
          context: ./tracker
          push: true
          tags: ghcr.io/orakysec/france-tracker:latest
